name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make MAKE_RELEASE=1
      run: make MAKE_RELEASE=1
    - name: test
      run: ./build_release/chess test
